language: generic 
sudo: required
services:
  - docker
  
before_install:
  - docker build -t amanbawa1996/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true amanbawa1996/react-test npm run test
  
after_success:
  - docker build -t amanbawa1996/multi-client ./client
  - docker build -t amanbawa1996/multi-nginx ./nginx
  - docker build -t amanbawa1996/multi-server ./server
  - docker build -t amanbawa1996/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take images and push to docker hub
  - docker push amanbawa1996/multi-client
  - docker push amanbawa1996/multi-nginx
  - docker push amanbawa1996/multi-server
  - docker push amanbawa1996/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-959434322448'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
  
