version: 3
services:
  client:
    image: "amanbawa1996/multi-client"
    host_name: client
    mem_limit: 128m
  worker:
    image: "amanbawa1996/multi-worker"
    host_name: worker
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "amanbawa1996/multi-nginx"
    host_name: nginx
    mem_limit: 128m
    ports:
      - "80:80"
  server:
    image: "amanbawa1996/multi-server"
    host_name: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
